apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue-db
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogue-db
  template:
    metadata:
      labels:
        app: catalogue-db
    spec:
      containers:
        - name: catalogue-db
          image: 746227194679.dkr.ecr.us-east-1.amazonaws.com/catalogue-db:latest
          imagePullPolicy: Always
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "admin"
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "true"
            - name: MYSQL_DATABASE
              value: "socksdb"
          ports:
            - containerPort: 3306