apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogue
  template:
    metadata:
      labels:
        app: catalogue
    spec:
      containers:
        - name: catalogue
          image: weaveworksdemos/catalogue:0.3.5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80