apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/mohamedwaleed98/ecommerce-microservices-demo.git.git
    targetRevision: main
    path: deploy/k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce

  syncPolicy:
    automated:
      prune: true
      selfHeal: true