name: Deploy to EKS

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Push Images to ECR"]
    types:
      - completed

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  CLUSTER_NAME: ecommerce-main-eks
  ECR_REGISTRY: 746227194679.dkr.ecr.us-east-1.amazonaws.com
  NAMESPACE: ecommerce

jobs:
  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::746227194679:role/GitHubActionsEcrPushRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: latest

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region "$AWS_REGION" \
            --name "$CLUSTER_NAME"

      - name: Apply namespace
        run: |
          kubectl apply -f deploy/kubernetes/namespace.yaml

      - name: Apply base manifests
        run: |
          kubectl apply -f deploy/k8s/catalogue-db-deployment.yaml
          kubectl apply -f deploy/k8s/catalogue-db-service.yaml
          kubectl apply -f deploy/k8s/catalogue-deployment.yaml
          kubectl apply -f deploy/k8s/catalogue-service.yaml
          kubectl apply -f deploy/k8s/front-end-deployment.yaml
          kubectl apply -f deploy/k8s/front-end-service.yaml
          kubectl apply -f deploy/k8s/ingress.yaml

      - name: Update catalogue-db image
        run: |
          kubectl set image deployment/catalogue-db \
            catalogue-db=$ECR_REGISTRY/catalogue-db:latest \
            -n $NAMESPACE

      - name: Update front-end image
        run: |
          kubectl set image deployment/front-end \
            front-end=$ECR_REGISTRY/front-end:latest \
            -n $NAMESPACE

      - name: Restart catalogue deployment
        run: |
          kubectl rollout restart deployment/catalogue -n $NAMESPACE

      - name: Wait for rollouts
        run: |
          kubectl rollout status deployment/catalogue-db -n $NAMESPACE --timeout=300s
          kubectl rollout status deployment/catalogue -n $NAMESPACE --timeout=300s
          kubectl rollout status deployment/front-end -n $NAMESPACE --timeout=300s

      - name: Show current resources
        run: |
          kubectl get pods -n $NAMESPACE
          kubectl get svc -n $NAMESPACE
          kubectl get ingress -n $NAMESPACE